[project]
name = "github"
version = "0.1.0"
description = "GitHub agent that detects code changes and updates README"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.119.0",
    "uvicorn>=0.37.0",
]
